
ALTER TABLE "USER" ADD INSTITUTION_ID NUMBER;

ALTER TABLE "USER"
    ADD CONSTRAINT FK_USER_INSTITUTION
    FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID)
    ON DELETE SET NULL;

CREATE INDEX IDX_USER_INSTITUTION ON "USER"(INSTITUTION_ID);


-- ---- 2. USER <-> RESEARCH_AREA (M:N) --------------------------------
-- "Which researchers specialize in Database Systems?" /
-- "Which research areas does this researcher work in?"
CREATE TABLE USER_RESEARCH_AREA (
    USER_ID NUMBER NOT NULL,
    AREA_ID NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, AREA_ID),
    CONSTRAINT FK_URA_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_URA_AREA FOREIGN KEY (AREA_ID) REFERENCES RESEARCH_AREA(AREA_ID) ON DELETE CASCADE
);

-- USER_ID is already the leading column of the PK (so lookups by user
-- are fast); this covers the reverse direction ("who works in area X").
CREATE INDEX IDX_URA_AREA ON USER_RESEARCH_AREA(AREA_ID);


-- ---- 3. PUBLICATION <-> RESEARCH_AREA (M:N) -------------------------
-- "How many publications exist in Artificial Intelligence?" /
-- "Which research areas does this paper belong to?"
CREATE TABLE PUBLICATION_RESEARCH_AREA (
    PUBLICATION_ID NUMBER NOT NULL,
    AREA_ID        NUMBER NOT NULL,
    PRIMARY KEY (PUBLICATION_ID, AREA_ID),
    CONSTRAINT FK_PRA_PUB  FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(PUBLICATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRA_AREA FOREIGN KEY (AREA_ID)        REFERENCES RESEARCH_AREA(AREA_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_PRA_AREA ON PUBLICATION_RESEARCH_AREA(AREA_ID);


-- ---- 4. PROJECT <-> RESEARCH_AREA (M:N) -----------------------------
-- "Which projects are related to Machine Learning?" — explicitly
-- listed as justified in the original master plan (section 7).
CREATE TABLE PROJECT_RESEARCH_AREA (
    PROJECT_ID NUMBER NOT NULL,
    AREA_ID    NUMBER NOT NULL,
    PRIMARY KEY (PROJECT_ID, AREA_ID),
    CONSTRAINT FK_PJRA_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PJRA_AREA    FOREIGN KEY (AREA_ID)    REFERENCES RESEARCH_AREA(AREA_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_PJRA_AREA ON PROJECT_RESEARCH_AREA(AREA_ID);

COMMIT;

