-- ================================================================
-- RPMS - Research & Publication Management System
-- Oracle schema
--
-- Run as the RPMS schema owner (default: rpms_user), e.g.
--   sqlplus rpms_user/your_password@localhost:1521/orcl @schema.sql
--
-- Use reset.sql first if you need to drop the existing objects.
-- ================================================================

-- 1. ROLE Table
CREATE TABLE "ROLE" (
    ROLE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME   VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(255)
);

-- 2. USER Table
-- FK is intentionally RESTRICT (no ON DELETE clause): ROLE_ID is NOT NULL, so
-- ON DELETE SET NULL would fail at runtime with ORA-01407 the first time a role
-- was deleted. Roles must be reassigned before a role row can be removed.
CREATE TABLE "USER" (
    USER_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FULL_NAME          VARCHAR2(100) NOT NULL,
    EMAIL              VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD           VARCHAR2(255) NOT NULL,
    DEPARTMENT         VARCHAR2(100),
    ORCID              VARCHAR2(50),
    TWO_FACTOR_ENABLED NUMBER(1) DEFAULT 0 CHECK (TWO_FACTOR_ENABLED IN (0, 1)),
    ROLE_ID            NUMBER NOT NULL,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES "ROLE"(ROLE_ID)
);

-- 3. INSTITUTION Table
CREATE TABLE INSTITUTION (
    INSTITUTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME           VARCHAR2(150) NOT NULL,
    COUNTRY        VARCHAR2(100) NOT NULL,
    WEBSITE        VARCHAR2(200)
);

-- 4. RESEARCH AREA Table
CREATE TABLE RESEARCH_AREA (
    AREA_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AREA_NAME   VARCHAR2(150) NOT NULL UNIQUE,
    DESCRIPTION CLOB
);

-- 5. VENUE Table (Conferences & Journals)
CREATE TABLE VENUE (
    VENUE_ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME                VARCHAR2(150) NOT NULL,
    TYPE                VARCHAR2(50) NOT NULL CHECK (TYPE IN ('Conference', 'Journal')),
    SUBMISSION_DEADLINE DATE,
    STATUS              VARCHAR2(50) DEFAULT 'Open'
);

-- 6. PUBLICATION Table
CREATE TABLE PUBLICATION (
    PUBLICATION_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE               VARCHAR2(250) NOT NULL,
    ABSTRACT            CLOB,
    DOI                 VARCHAR2(100) UNIQUE,
    SUBMISSION_DATE     DATE DEFAULT SYSDATE,
    TOTAL_VIEWS         NUMBER DEFAULT 0,
    TOTAL_DOWNLOADS     NUMBER DEFAULT 0,
    CONFIRMATION_STATUS VARCHAR2(50) DEFAULT 'Pending',
    VENUE_ID            NUMBER,
    USER_ID             NUMBER NOT NULL,
    CONSTRAINT FK_PUB_VENUE FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID) ON DELETE SET NULL,
    CONSTRAINT FK_PUB_USER  FOREIGN KEY (USER_ID)  REFERENCES "USER"(USER_ID) ON DELETE CASCADE
);

-- 7. AUTHOR_PUBLICATION Junction Table (M:N 'WRITES' relationship)
CREATE TABLE AUTHOR_PUBLICATION (
    USER_ID        NUMBER NOT NULL,
    PUBLICATION_ID NUMBER NOT NULL,
    AUTHOR_ROLE    VARCHAR2(50) DEFAULT 'Primary',
    PRIMARY KEY (USER_ID, PUBLICATION_ID),
    CONSTRAINT FK_AP_USER FOREIGN KEY (USER_ID)        REFERENCES "USER"(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_AP_PUB  FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(PUBLICATION_ID) ON DELETE CASCADE
);

-- 8. FILE Table
CREATE TABLE "FILE" (
    FILE_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_NAME      VARCHAR2(255) NOT NULL,
    FILE_TYPE      VARCHAR2(50),
    FILE_SIZE      NUMBER,
    UPLOAD_DATE    DATE DEFAULT SYSDATE,
    PUBLICATION_ID NUMBER NOT NULL,
    CONSTRAINT FK_FILE_PUB FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(PUBLICATION_ID) ON DELETE CASCADE
);

-- 9. REVIEW Table
CREATE TABLE REVIEW (
    REVIEW_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SCORE                  NUMBER(4, 2) CHECK (SCORE >= 1 AND SCORE <= 10),
    ORIGINALITY            NUMBER(5, 2) CHECK (ORIGINALITY >= 0 AND ORIGINALITY <= 100),
    OVERALL_RECOMMENDATION VARCHAR2(50),
    COMMENTS_AUTHOR        CLOB,
    COMMENTS_EDITOR        CLOB,
    DEADLINE               DATE NOT NULL,
    STATUS                 VARCHAR2(50) DEFAULT 'Pending',
    PUBLICATION_ID         NUMBER NOT NULL,
    REVIEWER_ID            NUMBER NOT NULL,
    CONSTRAINT FK_REV_PUB  FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(PUBLICATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REV_USER FOREIGN KEY (REVIEWER_ID)    REFERENCES "USER"(USER_ID) ON DELETE CASCADE,
    -- A reviewer is only assigned to a given publication once.
    CONSTRAINT UQ_REVIEW_ASSIGNMENT UNIQUE (PUBLICATION_ID, REVIEWER_ID)
);

-- 10. PROJECT Table
CREATE TABLE PROJECT (
    PROJECT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE      VARCHAR2(200) NOT NULL,
    STATUS     VARCHAR2(50) DEFAULT 'Planned',
    TIMELINE   VARCHAR2(100),
    BUDGET     NUMBER(15, 2),
    MANAGER_ID NUMBER NOT NULL,
    CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE
);

-- 11. FUNDING BODY Table
CREATE TABLE FUNDING_BODY (
    BODY_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME              VARCHAR2(150) NOT NULL UNIQUE,
    ORGANIZATION_TYPE VARCHAR2(100)
);

-- 12. GRANT Table (relationship between Project and Funding Body)
CREATE TABLE GRANT_FUNDING (
    GRANT_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AMOUNT     NUMBER(15, 2) NOT NULL CHECK (AMOUNT > 0),
    PROJECT_ID NUMBER NOT NULL,
    BODY_ID    NUMBER NOT NULL,
    CONSTRAINT FK_GRANT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_GRANT_BODY    FOREIGN KEY (BODY_ID)    REFERENCES FUNDING_BODY(BODY_ID) ON DELETE CASCADE
);

-- 13. AWARD Table
CREATE TABLE AWARD (
    AWARD_ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AWARD_NAME            VARCHAR2(150) NOT NULL,
    CATEGORY              VARCHAR2(100),
    AWARDING_ORGANIZATION VARCHAR2(150),
    USER_ID               NUMBER NOT NULL,
    CONSTRAINT FK_AWARD_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE
);

-- 14. MODERATION QUEUE Table
CREATE TABLE MODERATION_QUEUE (
    MOD_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_TYPE    VARCHAR2(50) NOT NULL,
    REFERENCE_ID NUMBER NOT NULL,
    FLAG_REASON  CLOB NOT NULL,
    STATUS       VARCHAR2(50) DEFAULT 'Pending',
    ACTION_TAKEN VARCHAR2(100)
);

-- 15. NOTIFICATION Table
CREATE TABLE NOTIFICATION (
    NOTIF_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CATEGORY   VARCHAR2(50),
    MESSAGE    CLOB NOT NULL,
    IS_READ    NUMBER(1) DEFAULT 0 CHECK (IS_READ IN (0, 1)),
    CREATED_AT DATE DEFAULT SYSDATE,
    USER_ID    NUMBER NOT NULL,
    CONSTRAINT FK_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID) ON DELETE CASCADE
);

-- ================================================================
-- Indexes on foreign keys (Oracle does not create these automatically;
-- without them the app's JOIN-heavy list queries do full table scans).
-- ================================================================
CREATE INDEX IDX_USER_ROLE       ON "USER"(ROLE_ID);
CREATE INDEX IDX_PUB_USER        ON PUBLICATION(USER_ID);
CREATE INDEX IDX_PUB_VENUE       ON PUBLICATION(VENUE_ID);
CREATE INDEX IDX_FILE_PUB        ON "FILE"(PUBLICATION_ID);
CREATE INDEX IDX_REVIEW_PUB      ON REVIEW(PUBLICATION_ID);
CREATE INDEX IDX_REVIEW_REVIEWER ON REVIEW(REVIEWER_ID);
CREATE INDEX IDX_PROJECT_MANAGER ON PROJECT(MANAGER_ID);
CREATE INDEX IDX_GRANT_PROJECT   ON GRANT_FUNDING(PROJECT_ID);
CREATE INDEX IDX_GRANT_BODY      ON GRANT_FUNDING(BODY_ID);
CREATE INDEX IDX_AWARD_USER      ON AWARD(USER_ID);
CREATE INDEX IDX_NOTIF_USER      ON NOTIFICATION(USER_ID);

COMMIT;
